services:
  portfolio:
    image: ghcr.io/vanduc2514/portfolio:main
    container_name: portfolio
    restart: unless-stopped
    networks:
      - gateway_external-routing
    labels:
      - traefik.enable=true
      - traefik.http.routers.portfolio.rule=Host(`vanduc2514.io.vn`) || Host(`nvduc.dev`)
      - traefik.http.routers.portfolio.service=portfolio
      # TODO: Change image COMMAND to open port 80
      - traefik.http.services.portfolio.loadbalancer.server.port=3000

networks:
  gateway_external-routing:
    external: true
