services:
  traefik:
    image: traefik:v3.3.2
    container_name: traefik
    restart: unless-stopped
    entrypoint:
      - /custom-entrypoint.sh
    environment:
      TRAEFIK_PLUGIN_KEYCLOAKOPENID_CLIENT_ID:
        ${TRAEFIK_PLUGIN_KEYCLOAKOPENID_CLIENT_ID}
      TRAEFIK_PLUGIN_KEYCLOAKOPENID_CLIENT_SECRET:
        ${TRAEFIK_PLUGIN_KEYCLOAKOPENID_CLIENT_SECRET}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/ssl/certs:/etc/ssl/certs/host:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic:/etc/traefik/dynamic
      - ./custom-entrypoint.sh:/custom-entrypoint.sh:ro
    networks:
      - external-routing
      - cloudflared

  cloudflared:
    image: cloudflare/cloudflared:2025.2.0
    container_name: cloudflared
    restart: unless-stopped
    command: ["tunnel", "run"]
    depends_on:
      - traefik
    user: "1000"
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN}
    networks:
      - cloudflared

  whoami:
    image: traefik/whoami:v1.10
    container_name: whoami
    restart: unless-stopped
    user: "1000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.vanduc2514.io.vn`)
      - traefik.http.routers.whoami.service=whoami
      - traefik.http.services.whoami.loadbalancer.server.port=80
    networks:
      - external-routing

networks:
  external-routing:
  cloudflared:
