services:
  traefik:
    build:
      context: ../../images/traefik
      args:
        TRAEFIK_PLUGIN_KEYCLOAKOPENID_CLIENT_SECRET: ${TRAEFIK_PLUGIN_KEYCLOAKOPENID_CLIENT_SECRET}
    image: traefik:v3.3.2-homelab-v1
    container_name: traefik
    restart: unless-stopped
    user: 1000:docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/ssl/certs:/etc/ssl/certs
    networks:
      - external-routing
      - cloudflared
  
  cloudflared:
    image: cloudflare/cloudflared:2025.1.0
    container_name: cloudflared
    restart: unless-stopped
    user: "1000"
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN}
    networks:
      - cloudflared

  whoami:
    image: traefik/whoami:v1.10
    container_name: whoami
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=external-routing
      - traefik.http.routers.whoami.rule=Host(`whoami.vanduc2514.io.vn`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.services.whoami.loadbalancer.server.port=80
    networks:
      - external-routing

networks:
  external-routing:
  cloudflared:
