# Logging configuration
log:
  # Set log level to DEBUG for detailed logging during development
  # Available levels: ERROR, DEBUG, PANIC, FATAL, WARN, INFO
  level: DEBUG

# Define entry points for incoming traffic
entryPoints:
  # HTTP entry point on port 80
  web:
    address: ":80"
  
  # HTTPS entry point on port 443
  websecure:
    address: ":443"

tls:
  # List of certificates for different domains
  # Note: All certificate files must be mounted in Docker container to /etc/ssl/certs/
  certificates:
    # Certificate for *.vanduc2514.io.vn
    - certFile: /etc/ssl/certs/vanduc2514.io.vn.tld.pem
      keyFile: /etc/ssl/certs/vanduc2514.io.vn.tld.key
    # Certificate for *.nvduc.dev
    - certFile: /etc/ssl/certs/nvduc.dev.tld.pem
      keyFile: /etc/ssl/certs/nvduc.dev.tld.key

# HTTP configuration for Traefik
http:
  middlewares:
    # Used for applications that don't provide their own OAuth capability
    forward-auth-keycloak:
      plugin:
        keycloakopenid:
          # Keycloak server URL for authentication
          KeycloakURL: https://auth.vanduc2514.io.vn
          
          # OAuth client credentialsm configured in Keycloak server
          ClientID: cloudflared-web-client
          ClientSecret: ${TRAEFIK_PLUGIN_KEYCLOAKOPENID_CLIENT_SECRET}
          
          # Keycloak realm configuration
          KeycloakRealm: master
          
          # OAuth scope requested during authentication
          Scope: openid profile email
          
          # Name of the cookie that will store the authentication token
          TokenCookieName: AUTH_WEB_CLIENT_HOMELAB
          
          # Disable sending authentication in headers
          # Authentication will be handled via cookies instead
          UseAuthHeader: false
          
          # Paths to exclude from authentication
          # Common for resources that don't require auth
          IgnorePathPrefixes: /favicon.ico

# Configure providers that Traefik will use to discover services
providers:
  # Docker provider configuration
  docker:
    # Unix socket to communicate with Docker daemon
    # Note: This socket must be mounted in the Traefik container
    endpoint: "unix:///var/run/docker.sock"
    # Services must be explicitly enabled in Docker labels
    exposedByDefault: false
  
  # File provider configuration
  file:
    # Directory containing additional static configurations
    # Note: This directory is COPY'd into the Docker container via Dockerfile
    directory: /etc/traefik/static

# Experimental features configuration
experimental:
  # Plugin configuration
  plugins:
    # Keycloak OpenID plugin for authentication
    keycloakopenid:
      moduleName: "github.com/Gwojda/keycloakopenid"
      version: "v0.1.35"
